language: node_js
node_js:
  -"stable"
branches:
  only:
  - main

cache:
  directories:
  - node_modules

install:
  - npm install
  - npminstall -g yarn
  
script:
  #- yarn lint
  - yarn build
  - mv build/index.html build/404.html  
  deploy:
    providers: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
      branch: main