language: node_js
node_js:
  - 8
install:
  - npm install -g zcatalyst-cli
jobs:
  include:
    - stage: functions
      before_script:
        - cd functions/catly/server
      script:
        - echo 'function!!'
        - echo 'Installing Deps!'
        - npm install
      after_success:
        - echo 'deploying function!'
        - catalyst deploy --only functions --project 700000000045014 --verbose
    - stage: client
      script:
        - echo 'deploying client!!'
	    - catalyst deploy --only client --project700000000045014 --verbose